### ISSUE TITLE
`main` field in `package.json`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#141] opened 2020-10-28 05:45 UTC
The `browser` field already pointed to `meriyah.umd.js`, shouldn't `main` point to `meriyah.cjs.js`?

And `browser` might want use the minified version?

**Comment by 3cp** [comment] 2020-10-28 05:52
I guess the benefit is that the umd main allows jsdelivr (or unpack) to serve umd as default main. So the short url can be used in `<script>` tag without any module loader.

https://cdn.jsdelivr.net/npm/meriyah@3.1.0 is same as the full path https://cdn.jsdelivr.net/npm/meriyah@3.1.0/dist/meriyah.umd.min.js

**Comment by fisker** [comment] 2020-10-28 05:55
As I understand `jsdelivr` looks for `browser`

https://github.com/prettier/prettier/pull/8387#issuecomment-633232840

We can add `unpkg` field for `unpkg`

**Comment by fisker** [comment] 2020-10-28 05:56
Configuring a default file in package.json
For packages hosted on npm, we support setting a "default" file for each package. This file is displayed at the top of directory listings on our website and available under shorter URL on the CDN. The default file can be configured by setting one of the following fields in package.json (ordered by priority):

jsdelivr
browser
main

Copied from https://www.jsdelivr.com/features

**Comment by 3cp** [comment] 2020-10-28 06:01
Thx! Good to know. It's @KFlash's call.
Note this is a breaking change.

**Comment by benmccann** [comment] 2021-02-09 23:36
I am unable to use Meriyah 4.1.1 in my project. It looks like this may have been attempted to be fixed in https://github.com/meriyah/meriyah/pull/171, but it doesn't seem sufficient for me.

```
node_modules/.pnpm/meriyah@4.1.1/node_modules/meriyah/dist/meriyah.umd.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/.pnpm/meriyah@4.1.1/node_modules/meriyah/dist/meriyah.umd.js
require() of ES modules is not supported.
require() of node_modules/.pnpm/meriyah@4.1.1/node_modules/meriyah/dist/meriyah.umd.js from packages/kit/src/api/dev/transform.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename meriyah.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/.pnpm/meriyah@4.1.1/node_modules/meriyah/package.json.
```

Changing `main` to `meriyah.cjs.js` as suggested in this issue fixes it for me. @KFlash is that a change we could make?

**Comment by KFlash** [comment] 2021-02-09 23:39
i think it's reasonable. Depends on older browsers and NodeJS I guess. Wanna do a pr?
cc / @3cp

**Comment by 3cp** [comment] 2021-02-10 08:10
@benmccann what nodejs version you got problem with meriyah 4.1.1? If possible, can you push up a simple github repo to reproduce the error?

**Comment by 3cp** [comment] 2021-02-10 08:14
I had no issue with nodejs v10, v12, v14, and v15. You probably found some interesting edge case.

**Comment by 3cp** [comment] 2021-02-10 08:16
I am guessing you are on an early v12 (but not latest v12) which got esm support, but not `exports.require` support.

**Comment by benmccann** [comment] 2021-02-10 13:53
I'm on Node 14.8.0. I'm not sure whether I'll be able to setup a repro. I do have `"type": "module"` in my project. I'm not sure if there's anything else that might affect it

**Comment by 3cp** [comment] 2021-02-10 14:12
Try upgrade to latest v14.
The exports.require may not be supported by your nodejs version.

**Comment by 3cp** [comment] 2021-02-10 14:14
I agree using .cjs on main field can better support what ever nodejs versions.

**Closed** 2021-02-10 14:31 UTC
