### ISSUE TITLE
The type `BindingPattern` may be incorrect

### ISSUE THREAD

**Issue by xuld** [meriyah/meriyah#34] opened 2019-08-12 03:49 UTC
The source of `BindingPattern` is (estree.ts#137):
````ts
export type BindingPattern =
  | ArrayPattern
  | ObjectPattern
  | ArrayExpression
  | AssignmentExpression
  | ObjectExpression
  | Identifier;
export type BindingName = BindingPattern | Identifier;
```

1. Will `BindingPattern` be  `ArrayExpression | AssignmentExpression | ObjectExpression`?
2. What's the difference between `BindingPattern` and `BindingName`?
3. `VariableDeclarator.id` is defined as `Expression | BindingName`, but when will `VariableDeclarator.id` be `Expression`?

---
Another question: When `ClassProperty` will be used instead of `FieldDeclaration`?

**Comment by KFlash** [comment] 2019-08-12 04:33
@xuld Hi. You shouldn't blindly follow the ESTree types in Meriyah because the parser uses a internal module system and parses things in a different way even the output will be correct.  E.g. in `ESTree` the `YieldExpression` is part of the `AssignmentExpression` and same in the ECMA specs. In Meriyah this is part of `PrimaryExpressionExtended`.

Regarding the `BindingPattern` it looks incorrect, and it maybe would have been better if it was written `BindingPattern  |  ArrayExpression  |  AssignmentExpression`.

To answer your questions

1. In Meriyah yes. It depends if you pass `isPattern` function arg or not.  In the ECMA specs you have both `AssignmentPattern` and `AssignmentExpression` separated, but in this parser they are the same. 

2. `BindingPattern` also include `ObjectPattern` and `ArrayPattern`. A `BindingName` is the `Identifier`. I see the confusion here, so maybe that should be fixed differently.

3. See bullet 1. It all depends on the function args you are passing.

Meriyah was designed this way because of performance and to lower the memory usage. Maybe little hard to understand, but to do a comparison - also Acorn's TS types isn't equal to ESTree itself and also have different names from what is mentioned in the ECMA specs.

**Comment by KFlash** [comment] 2019-08-12 04:51
Made a little "fix" for this. Hope that helps :)

**Closed** 2019-08-12 04:51 UTC

**Comment by xuld** [comment] 2019-08-12 04:54
It' ok that `ArrayExpression` and `ArrayPattern` are both returned by a same function(`parseArrayExpressionOrPattern`)

In fact, the return type of parseArrayExpressionOrPattern is determined by the parameter `isPattern`, and in `parseBindingPattern`, the `isPattern` argument is always true:

```ts
function parseBindingPattern(/*...*/) {
  // ...
 const left =
    parser.token === Token.LeftBracket
      ? parseArrayExpressionOrPattern(parser, context, scope, 1, 0, 1, type, origin, start, line, column)
      : parseObjectLiteralOrPattern(parser, context, scope, 1, 0, 1, type, origin, start, line, column);
   // ...
   return left
}
```
So `parseBindingPattern` will never return `ArrayExpression`

It will be better to use method overloading here:

```ts
function parseArrayExpressionOrPattern(isPattern: true): ArrayPattern 
function parseArrayExpressionOrPattern(isPattern: false): ArrayExpression

// or
function parseArrayExpressionOrPattern<T extends boolean>(isPattern: T): T extends true ? ArrayPattern : ArrayExpression
```

**Comment by KFlash** [comment] 2019-08-12 04:59
I agree with your in that, but I'm on mobile now and stuck with some other stuff. Could you do the change and open a PR ?

**Comment by xuld** [comment] 2019-08-12 07:52
I'd like to, but the project is too large and git clone fails several times, thanks to CN great wall

**Comment by KFlash** [comment] 2019-08-12 09:07
Ok. I will look into this soon as I'm finished with what I'm doing ATM - creating the worlds fastest regex validator 👍

**Comment by KFlash** [comment] 2019-08-12 11:18
@aladdin-add Is this something you could look into and fix?
