### ISSUE TITLE
Unexpected token after do...while statement

### ISSUE THREAD

**Issue by davidbonnet** [meriyah/meriyah#20] opened 2019-07-14 19:32 UTC
Hats off to the design and performance of this insanely great parser. 👍 

It would be a great companion to [Astring](https://github.com/davidbonnet/astring) once this is resolved: the following code (which comes from [here](https://github.com/davidbonnet/astring/blob/master/src/tests/fixtures/tree/es6.js#L195)) provokes an error:
```js
do;while(0) 0;
```

**Comment by KFlash** [comment] 2019-07-14 22:53
Hi. That's actually not an bug. The issue is that all parsers include V8 have implemented this wrong. 

`doStatement[?Yield, ?Await, ?Return]while(Expression[+In, ?Yield, ?Await] ) ; `

**Note** the semicolon at the end, and it's not optional.

Would it be easier if I provide a option to workaround this?

**Comment by axefrog** [comment] 2019-07-15 00:43
It's an interesting question - purity vs pragmatism - if the majority of the world's JavaScript engines have edge cases that deviate from the spec, and we assume that Meriyah is being used to support software that runs in these environments, is it better to support these edge cases as de facto standards? How much does a workaround force you to introduce undesirable behaviour into the code? Is there another approach, such as assuming correct syntax at first, but then catching errors at the entrypoint and matching those errors to known non-standard edge cases? What about, at the point where you're about to throw an error, switch to a slow path that allows for a certain amount of back-tracking to handle these cases? Throwing errors is of course inherently expensive, so naturally that would seem to be a suitable place to employ edge case detection without impacting performance in the hot path,

**Comment by KFlash** [comment] 2019-07-15 01:15
I agree this is an interesting case, and kind of hard to directly solve it because Meriyah should be 100% spec compatible, and disallow backtracking and "*lookaheads*" to reduce memory usage. That¨s the design idea behind this parser. Then again it would be easier if other parsers followed the specs, but as in this case this edge cases seem to be a de facto standard.

The only solution for this is to introduce another option to allow such cases. A bit mask is less expensive than error recovery :) And I'm in a unique situation that I have the knowledge about every bug in other parsers and all spec differences between Meriyah and other parsers / javascript engines so it shouldn't be to difficult to implement.

@axefrog Any idea about a name on the new option?

Btw. I plan to implement error recovery later on such as I'm done with my TypeScript parser.

**Comment by KFlash** [comment] 2019-07-15 01:46
I think I solved in. You can use the new `deFacto` option. I also updated the [REPL](https://meriyah.github.io/meriyah/) to accept the new option. Just enable `Allow spec deviaton`.

**Comment by KFlash** [comment] 2019-07-15 11:15
I'm closing this as solved.

**Closed by KFlash** 2019-07-15 11:15 UTC

**Comment by davidbonnet** [comment] 2019-07-15 18:44
It does, awesome!
